#%RAML 0.8
title: Task
mediaType: application/json
baseUri: https://api.built.io/v1/classes
traits:
  - builtIoResource: !include builtio/builtioHeaders.yml
resourceTypes:
  - collection: !include builtio/collection.yml
  - member: !include builtio/member.yml

# stuff below is generated on resource basis
schemas:
 - tasks: !include schemas/tasks.json
 - task: !include schemas/task.json

/task.json:
  type: collection
/task/objects/{id}.json:
  type: member
